In [5]:
import cloudscraper
#Creates cloud scraper to bypass cloudflare
scraper = cloudscraper.create_scraper()
#Gets market index cookie.
scraper.get("https://www.marketindex.com.au")

In [9]:
ticker = "COF"
limit = 20
url = f"https://data-api.marketindex.com.au/api/v1/announcements?codes={ticker}%3AAUD%3AXASX&limit={limit}"
response = scraper.get(url=url)
response.raise_for_status()
response.json()["data"]["announcements"]

[{'id': 2029956,
  'identifier': 'XASX:COF:2A1654634',
  'fileId': '2A1654634',
  'pageCount': 25,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 846523,
  'heading': 'Change in substantial holding',
  'dateTime': '2026-02-19T21:20:50.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2026/02/20/2A1654634.pdf',
  'types': [{'id': 5, 'identifier': '5', 'title': 'Security Holder Notices'}]},
 {'id': 2023403,
  'identifier': 'XASX:COF:2A1651396',
  'fileId': '2A1651396',
  'pageCount': 33,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 6901467,
  'heading': 'COF HY26 Property Compendium',
  'dateTime': '2026-02-03T22:15:26.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651396.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023407,
  'identifier': 'XASX:COF:2A1651393',
  'fileId': '2A1651393',
  'pageCount': 37,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 9235455,
  'heading': 'COF HY26 Results Presentation',
  'dateTime': '2026-02-03T22:14:56.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651393.pdf',
  'types': [{'id': 15, 'identifier': '15', 'title': 'Other'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023401,
  'identifier': 'XASX:COF:2A1651392',
  'fileId': '2A1651392',
  'pageCount': 3,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 491231,
  'heading': 'COF HY26 Results Announcement',
  'dateTime': '2026-02-03T22:14:16.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651392.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023390,
  'identifier': 'XASX:COF:2A1651390',
  'fileId': '2A1651390',
  'pageCount': 25,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 2702614,
  'heading': 'COF HY26 Financial Report',
  'dateTime': '2026-02-03T22:10:31.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651390.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023386,
  'identifier': 'XASX:COF:2A1651389',
  'fileId': '2A1651389',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 399472,
  'heading': 'COF HY26 Appendix 4D',
  'dateTime': '2026-02-03T22:07:06.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651389.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2019972,
  'identifier': 'XASX:COF:2A1649968',
  'fileId': '2A1649968',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 219614,
  'heading': 'HY26 Results Date & Webcast Details',
  'dateTime': '2026-01-27T23:36:53.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2026/01/28/2A1649968.pdf',
  'types': [{'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 2000324,
  'identifier': 'XASX:COF:2A1643755',
  'fileId': '2A1643755',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 243283,
  'heading': 'Chatswood office divested at 12.5% premium to book value',
  'dateTime': '2025-12-17T22:58:09.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/12/18/2A1643755.pdf',
  'types': [{'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 1994759,
  'identifier': 'XASX:COF:2A1641343',
  'fileId': '2A1641343',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 222346,
  'heading': 'December 2025 Distribution Declaration',
  'dateTime': '2025-12-04T22:20:24.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/12/05/2A1641343.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1994732,
  'identifier': 'XASX:COF:2A1641334',
  'fileId': '2A1641334',
  'pageCount': 4,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 13776,
  'heading': 'Dividend/Distribution - COF',
  'dateTime': '2025-12-04T22:09:09.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/12/05/2A1641334.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1976139,
  'identifier': 'XASX:COF:2A1632611',
  'fileId': '2A1632611',
  'pageCount': 2,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 276789,
  'heading': 'Q1 FY26 Operating Update',
  'dateTime': '2025-10-29T22:42:43.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/10/30/2A1632611.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1958849,
  'identifier': 'XASX:COF:2A1624965',
  'fileId': '2A1624965',
  'pageCount': 26,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 6014603,
  'heading': 'Appendix 4G and Corporate Governance Statement',
  'dateTime': '2025-09-29T05:44:15.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/09/29/2A1624965.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'},
   {'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 1958850,
  'identifier': 'XASX:COF:2A1624969',
  'fileId': '2A1624969',
  'pageCount': 41,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 8773432,
  'heading': '2025 Annual Report',
  'dateTime': '2025-09-29T05:44:10.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/09/29/2A1624969.pdf',
  'types': [{'id': 3, 'identifier': '3', 'title': 'Annual Reports'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1947769,
  'identifier': 'XASX:COF:2A1619741',
  'fileId': '2A1619741',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 222328,
  'heading': 'September 2025 Distribution Declaration',
  'dateTime': '2025-09-04T23:09:36.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/09/05/2A1619741.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1947760,
  'identifier': 'XASX:COF:2A1619740',
  'fileId': '2A1619740',
  'pageCount': 4,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 13771,
  'heading': 'Dividend/Distribution - COF',
  'dateTime': '2025-09-04T23:04:41.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/09/05/2A1619740.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1936347,
  'identifier': 'XASX:COF:2A1613876',
  'fileId': '2A1613876',
  'pageCount': 33,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 7005473,
  'heading': 'COF FY25 Property Compendium',
  'dateTime': '2025-08-14T23:19:03.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613876.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1936340,
  'identifier': 'XASX:COF:2A1613873',
  'fileId': '2A1613873',
  'pageCount': 35,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 8894144,
  'heading': 'COF FY25 Results Presentation',
  'dateTime': '2025-08-14T23:17:33.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613873.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'},
   {'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 1936337,
  'identifier': 'XASX:COF:2A1613870',
  'fileId': '2A1613870',
  'pageCount': 4,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 277898,
  'heading': 'COF FY25 Results Announcement',
  'dateTime': '2025-08-14T23:16:48.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613870.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1936339,
  'identifier': 'XASX:COF:2A1613868',
  'fileId': '2A1613868',
  'pageCount': 41,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 2433865,
  'heading': 'COF FY25 Financial Report',
  'dateTime': '2025-08-14T23:16:23.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613868.pdf',
  'types': [{'id': 3, 'identifier': '3', 'title': 'Annual Reports'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1936334,
  'identifier': 'XASX:COF:2A1613865',
  'fileId': '2A1613865',
  'pageCount': 2,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 403732,
  'heading': 'COF FY25 Appendix 4E',
  'dateTime': '2025-08-14T23:15:13.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613865.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]}]

In [ ]:
dd.get

In [16]:
import requests
import os
import time
from random import random
import pandas as pd
from datetime import datetime
import cloudscraper


class DocumentDownloader():
    def __init__(self):
        print("DocumentDownloader initialized...")

        #Creates cloud scraper to bypass cloudflare
        self.scraper = cloudscraper.create_scraper()
        #Gets market index cookie.
        self.scraper.get("https://www.marketindex.com.au")

        
    def get_announcements(self, ticker: str, limit: int = 20):
    
        url = f"https://data-api.marketindex.com.au/api/v1/announcements?codes={ticker}%3AAUD%3AXASX&limit={limit}"
        response = self.scraper.get(url=url)
        response.raise_for_status()
        return response.json()["data"]["announcements"]

    def download_pdf(self, identifier: str, filename:str, save_dir: str = "pdfs"):
        base_url = "https://data-api.marketindex.com.au/api/v1/announcements/"
        pdf_url = base_url + identifier + "/pdf"
        os.makedirs(save_dir, exist_ok=True)
        # filename = pdf_url.split("/")[-2]
        filepath = os.path.join(save_dir, filename)


        #Check if file already exists. Only executes if file does not exist. 
        if not os.path.exists(filepath):
        
            response = self.scraper.get(pdf_url)
            print(response)
            if response.status_code == 200:
                with open(filepath, "wb") as f:
                    f.write(response.content)
                    print(f"Downloaded: {filename}")
            else:
                print(f"Failed to download {filename}: {response.status_code}")


    def create_announcement_df(self, ticker_list:list,limit:int = 100):
    
        #Used for creating announcements dataframe.  
        ls_announcements = []

        #To be generalized in future to extract other documents such as sustainability reports and annual reports. 
        #Extracts only investor presentations.
        # 
        print("above ticker list") 
        for ticker in ticker_list:
            try:
                announcements = self.get_announcements(ticker,limit)

                print("announcements run here")
                for announcement in announcements:

                    #Check for whether announcement type is other; investor presentations are usuallly under 'other'. 
                    announcement_type = announcement['types'][0]['title']
                    announcement['ticker'] = ticker

                    print(ticker, announcement['heading'],announcement_type) 
                
                ls_announcements.extend(announcements)

                time.sleep(2 + random()*4)
                
            except Exception as e:
                print(f"Error processing {ticker}: {e}")

        return pd.DataFrame(ls_announcements)


    def filter_df_heading_with_regex(self, df:pd.DataFrame ,regex_pattern:str):
        return df[df['heading'].str.contains(regex_pattern,case = False,na=False)]

    def filter_df_with_date(self,df:pd.DataFrame, from_date_YYYY_MM_DD:str, to_date_YYYY_MM_DD:str):
        df["ISO_date"] = pd.to_datetime(df['dateTime'])
        return df[df["ISO_date"].between(from_date_YYYY_MM_DD, to_date_YYYY_MM_DD)]

    def filter_df_heading_with_regex_and_date(self,df:pd.DataFrame, regex_pattern:str, from_date_YYYY_MM_DD:str, to_date_YYYY_MM_DD:str):
        df_filtered = self.filter_df_heading_with_regex(df, regex_pattern)
        df_filtered = self.filter_df_with_date(df_filtered, from_date_YYYY_MM_DD, to_date_YYYY_MM_DD)
        return df_filtered

    def download_pdfs_in_df(self, df: pd.DataFrame, doc_suffix, save_dir: str):
        
        #If no doc suffix is provided, dd will use heading as the suffix. 

        try: 
            for index, row in df.iterrows():
                identifier = row['identifier']
                print("Downloading ",row['heading'], ".....")
                
                if doc_suffix is None:
                    filename = f"{row['ticker']}_{row['heading']}"
                else:
                    filename = f"{row['ticker']}_{doc_suffix}"

            
                self.download_pdf(identifier, filename, save_dir)
                time.sleep(3+random()*10)   # Sleep to avoid overwhelming the server

        except Exception as e:
            print(f"Error processing row {row}: {e}")

    # General method for downloading files. Regex needs to be specified. 
    def download_documents(self, ticker_list: list, from_date_YYYY_MM_DD:str, to_date_YYYY_MM_DD:str, save_dir: str, regex_pattern: str, doc_suffix = None ,limit: int = 100):
        """
        Downloads the investor presentations for the given ticker list.
        
        Parameters:
        - ticker_list: List of stock tickers to process.
        - limit: Number of announcements to fetch per ticker.
        - save_dir: Directory to save the downloaded PDFs.
        - regex_pattern: Regex pattern to filter the announcements.
        - from_date_YYYY_MM_DD: Start date in YYYY-MM-DD format.
        """
        df_announcements = self.create_announcement_df(ticker_list, limit)
        df_filtered = self.filter_df_heading_with_regex_and_date(df_announcements, regex_pattern, from_date_YYYY_MM_DD=from_date_YYYY_MM_DD, to_date_YYYY_MM_DD=to_date_YYYY_MM_DD)
        
        print(f"Filtered {len(df_filtered)} announcements matching the criteria.")
        
        
        self.download_pdfs_in_df(df_filtered, doc_suffix = doc_suffix, save_dir = save_dir)


    #Converts date to CY. 
    def assign_period_CY(self,date_input):
        
        if isinstance(date_input, str):
            date = datetime.strptime(date_input, "%Y-%m-%d")
        else:
            date = date_input

        if date.month in [1, 2, 3]:
            return f"CY{str(date.year - 1)[-2:]}"
        elif date.month in [7, 8, 9]:
            return f"HY{str(date.year)[-2:]}"
        else:
            return None
        
    #Converts date to FY. 
    def assign_period_FY(self,date_input):
        
        if isinstance(date_input, str):
            date = datetime.strptime(date_input, "%Y-%m-%d")
        else:
            date = date_input

        if date.month in [1, 2, 3]:
            return f"HY{str(date.year)[-2:]}"
        elif date.month in [7, 8, 9]:
            return f"FY{str(date.year)[-2:]}"
        else:
            return None

    def download_results_presentations(self, ticker_list: list, from_date_YYYY_MM_DD:str, to_date_YYYY_MM_DD:str, limit: int = 100, save_dir: str = "datasets/co_presentations", regex_pattern: str = r'results presentation|result presentation'):
        """
        Downloads the results presentations for the given ticker list.
        
        Parameters:
        - ticker_list: List of stock tickers to process.
        - limit: Number of announcements to fetch per ticker.
        - save_dir: Directory to save the downloaded PDFs.
        - regex_pattern: Regex pattern to filter the announcements.
        - from_date_YYYY_MM_DD: Start date in YYYY-MM-DD format.
        """
        df_announcements = self.create_announcement_df(ticker_list, limit)
        df_filtered = self.filter_df_heading_with_regex_and_date(df_announcements, regex_pattern, from_date_YYYY_MM_DD=from_date_YYYY_MM_DD, to_date_YYYY_MM_DD=to_date_YYYY_MM_DD)
        
        print(f"Filtered {len(df_filtered)} announcements matching the criteria.")
        
        # self.download_pdfs_in_df(df_filtered, save_dir)

        try: 
            for index, row in df_filtered.iterrows():
                identifier = row['identifier']
                fileType = row['fileType']
                
                print("Downloading ",row['heading'], ".....")
                
                CY = self.assign_period_FY(row["ISO_date"])

                filename = f"{row['ticker']}_{CY}_IP.{fileType}"
                print(filename)
                self.download_pdf(identifier, filename, save_dir)
                time.sleep(3+random()*10)   # Sleep to avoid overwhelming the server

        except Exception as e:
            print(f"Error processing row {row}: {e}")

# Instantiate Document Downloader

In [17]:
#Instantiate DocumentDownloader class
dd = DocumentDownloader()

DocumentDownloader initialized...

In [18]:
dd.get_announcements("COF")

[{'id': 2029956,
  'identifier': 'XASX:COF:2A1654634',
  'fileId': '2A1654634',
  'pageCount': 25,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 846523,
  'heading': 'Change in substantial holding',
  'dateTime': '2026-02-19T21:20:50.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2026/02/20/2A1654634.pdf',
  'types': [{'id': 5, 'identifier': '5', 'title': 'Security Holder Notices'}]},
 {'id': 2023403,
  'identifier': 'XASX:COF:2A1651396',
  'fileId': '2A1651396',
  'pageCount': 33,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 6901467,
  'heading': 'COF HY26 Property Compendium',
  'dateTime': '2026-02-03T22:15:26.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651396.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023407,
  'identifier': 'XASX:COF:2A1651393',
  'fileId': '2A1651393',
  'pageCount': 37,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 9235455,
  'heading': 'COF HY26 Results Presentation',
  'dateTime': '2026-02-03T22:14:56.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651393.pdf',
  'types': [{'id': 15, 'identifier': '15', 'title': 'Other'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023401,
  'identifier': 'XASX:COF:2A1651392',
  'fileId': '2A1651392',
  'pageCount': 3,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 491231,
  'heading': 'COF HY26 Results Announcement',
  'dateTime': '2026-02-03T22:14:16.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651392.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023390,
  'identifier': 'XASX:COF:2A1651390',
  'fileId': '2A1651390',
  'pageCount': 25,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 2702614,
  'heading': 'COF HY26 Financial Report',
  'dateTime': '2026-02-03T22:10:31.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651390.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2023386,
  'identifier': 'XASX:COF:2A1651389',
  'fileId': '2A1651389',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 399472,
  'heading': 'COF HY26 Appendix 4D',
  'dateTime': '2026-02-03T22:07:06.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2026/02/04/2A1651389.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 2019972,
  'identifier': 'XASX:COF:2A1649968',
  'fileId': '2A1649968',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 219614,
  'heading': 'HY26 Results Date & Webcast Details',
  'dateTime': '2026-01-27T23:36:53.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2026/01/28/2A1649968.pdf',
  'types': [{'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 2000324,
  'identifier': 'XASX:COF:2A1643755',
  'fileId': '2A1643755',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 243283,
  'heading': 'Chatswood office divested at 12.5% premium to book value',
  'dateTime': '2025-12-17T22:58:09.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/12/18/2A1643755.pdf',
  'types': [{'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 1994759,
  'identifier': 'XASX:COF:2A1641343',
  'fileId': '2A1641343',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 222346,
  'heading': 'December 2025 Distribution Declaration',
  'dateTime': '2025-12-04T22:20:24.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/12/05/2A1641343.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1994732,
  'identifier': 'XASX:COF:2A1641334',
  'fileId': '2A1641334',
  'pageCount': 4,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 13776,
  'heading': 'Dividend/Distribution - COF',
  'dateTime': '2025-12-04T22:09:09.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/12/05/2A1641334.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1976139,
  'identifier': 'XASX:COF:2A1632611',
  'fileId': '2A1632611',
  'pageCount': 2,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 276789,
  'heading': 'Q1 FY26 Operating Update',
  'dateTime': '2025-10-29T22:42:43.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/10/30/2A1632611.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1958849,
  'identifier': 'XASX:COF:2A1624965',
  'fileId': '2A1624965',
  'pageCount': 26,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 6014603,
  'heading': 'Appendix 4G and Corporate Governance Statement',
  'dateTime': '2025-09-29T05:44:15.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/09/29/2A1624965.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'},
   {'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 1958850,
  'identifier': 'XASX:COF:2A1624969',
  'fileId': '2A1624969',
  'pageCount': 41,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 8773432,
  'heading': '2025 Annual Report',
  'dateTime': '2025-09-29T05:44:10.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/09/29/2A1624969.pdf',
  'types': [{'id': 3, 'identifier': '3', 'title': 'Annual Reports'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1947769,
  'identifier': 'XASX:COF:2A1619741',
  'fileId': '2A1619741',
  'pageCount': 1,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 222328,
  'heading': 'September 2025 Distribution Declaration',
  'dateTime': '2025-09-04T23:09:36.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/09/05/2A1619741.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1947760,
  'identifier': 'XASX:COF:2A1619740',
  'fileId': '2A1619740',
  'pageCount': 4,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 13771,
  'heading': 'Dividend/Distribution - COF',
  'dateTime': '2025-09-04T23:04:41.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/09/05/2A1619740.pdf',
  'types': [{'id': 4, 'identifier': '4', 'title': 'Dividend Notices'}]},
 {'id': 1936347,
  'identifier': 'XASX:COF:2A1613876',
  'fileId': '2A1613876',
  'pageCount': 33,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 7005473,
  'heading': 'COF FY25 Property Compendium',
  'dateTime': '2025-08-14T23:19:03.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613876.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1936340,
  'identifier': 'XASX:COF:2A1613873',
  'fileId': '2A1613873',
  'pageCount': 35,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 8894144,
  'heading': 'COF FY25 Results Presentation',
  'dateTime': '2025-08-14T23:17:33.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613873.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'},
   {'id': 15, 'identifier': '15', 'title': 'Other'}]},
 {'id': 1936337,
  'identifier': 'XASX:COF:2A1613870',
  'fileId': '2A1613870',
  'pageCount': 4,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 277898,
  'heading': 'COF FY25 Results Announcement',
  'dateTime': '2025-08-14T23:16:48.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613870.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1936339,
  'identifier': 'XASX:COF:2A1613868',
  'fileId': '2A1613868',
  'pageCount': 41,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 2433865,
  'heading': 'COF FY25 Financial Report',
  'dateTime': '2025-08-14T23:16:23.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': False,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613868.pdf',
  'types': [{'id': 3, 'identifier': '3', 'title': 'Annual Reports'},
   {'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]},
 {'id': 1936334,
  'identifier': 'XASX:COF:2A1613865',
  'fileId': '2A1613865',
  'pageCount': 2,
  'symbolId': 'COF:AUD:XASX',
  'securityName': 'Centuria Office REIT',
  'fileSize': 403732,
  'heading': 'COF FY25 Appendix 4E',
  'dateTime': '2025-08-14T23:15:13.000Z',
  'fileType': 'pdf',
  'isPriceSensitive': True,
  'fileKey': 'announcements/xasx/2025/08/15/2A1613865.pdf',
  'types': [{'id': 2, 'identifier': '2', 'title': 'Periodic Reports'}]}]

In [19]:
dd.create_announcement_df(["COF"])

above ticker list
announcements run here
COF Change in substantial holding Security Holder Notices
COF COF HY26 Property Compendium Periodic Reports
COF COF HY26 Results Presentation Periodic Reports
COF COF HY26 Results Announcement Periodic Reports
COF COF HY26 Financial Report Periodic Reports
COF COF HY26 Appendix 4D Dividend Notices
COF HY26 Results Date & Webcast Details Other
COF Chatswood office divested at 12.5% premium to book value Other
COF December 2025 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF Q1 FY26 Operating Update Periodic Reports
COF Appendix 4G and Corporate Governance Statement Other
COF 2025 Annual Report Periodic Reports
COF September 2025 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF COF FY25 Property Compendium Periodic Reports
COF COF FY25 Results Presentation Other
COF COF FY25 Results Announcement Periodic Reports
COF COF FY25 Financial Report Annual Reports
COF COF FY25 Appendix 4E Periodic Reports
COF FY25 Results Date & Webcast Details Other
COF June 2025 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF Q3 FY25 Operating Update Periodic Reports
COF March 2025 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF COF HY25 Property Compendium Periodic Reports
COF COF HY25 Results Presentation Other
COF COF HY25 Results Announcement Periodic Reports
COF COF HY25 Financial Report Periodic Reports
COF COF HY25 Appendix 4D Dividend Notices
COF December 2024 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF 2024 Climate-related Disclosures Periodic Reports
COF 2024 Sustainability Report Other
COF Q1 FY25 Operating Update Periodic Reports
COF 2024 Annual Report Periodic Reports
COF Appendix 4G and Corporate Governance Statement Other
COF September 2024 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF Change in substantial holding Security Holder Notices
COF Change in substantial holding Security Holder Notices
COF COF FY24 Property Compendium Periodic Reports
COF COF FY24 Results Presentation Other
COF COF FY24 Results Announcement Periodic Reports
COF COF FY24 Financial Report Periodic Reports
COF COF FY24 Appendix 4E Periodic Reports
COF FY24 Results Date & Webcast Details Other
COF 555 Coronation Drive Settlement Other
COF FY24 Portfolio valuations Periodic Reports
COF June 2024 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF Non-core Toowong office divested addendum Other
COF Non-core Toowong office divested Other
COF Q3 FY24 Operating Update Periodic Reports
COF New COF Fund Manager Appointed Company Administration
COF March 2024 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF COF HY24 Property Compendium Periodic Reports
COF COF HY24 Results Presentation Periodic Reports
COF COF HY24 Results Announcement Periodic Reports
COF COF HY24 Financial Report Periodic Reports
COF COF HY24 Appendix 4D Periodic Reports
COF Significant Lease Renewal William Square, WA Other
COF 54 Marcus Clarke Street Settlement Other
COF HY24 Results Date & Webcast Details Other
COF HY24 Portfolio Valuations Periodic Reports
COF December 2023 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF Change in substantial holding Security Holder Notices
COF 2023 Sustainability Report Other
COF Ceasing to be a substantial holder Security Holder Notices
COF Q1 FY24 Operating Update Dividend Notices
COF Change in substantial holding Security Holder Notices
COF 2023 Annual Report Periodic Reports
COF Appendix 4G and Corporate Governance Statement Other
COF Change in substantial holding Security Holder Notices
COF September 2023 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF COF FY23 Property Compendium Periodic Reports
COF COF FY23 Results Presentation Other
COF COF FY23 Results Announcement Periodic Reports
COF COF FY23 Financial Report Annual Reports
COF COF FY23 Appendix 4E Periodic Reports
COF FY23 Results Date & Webcast Details Other
COF Divestment of 35 Robina Town Centre Drive, Robina QLD Other
COF FY23 Portfolio Valuations Periodic Reports
COF $225M Debt Refinance and Non-Core Divestment Other
COF June 2023 Distribution Declaration Dividend Notices
COF Dividend/Distribution - COF Dividend Notices
COF Q3 FY23 Operating Update Periodic Reports
COF Dividend/Distribution - COF Dividend Notices
COF March 2023 Distribution Declaration Dividend Notices
COF COF HY23 Property Compendium Periodic Reports
COF COF HY23 Results Presentation Other
COF COF HY23 Results Announcement Periodic Reports
COF COF HY23 Financial Report Periodic Reports
COF COF HY23 Appendix 4D Dividend Notices
COF HY23 Results Date & Webcast Details Other
COF Change in substantial holding Security Holder Notices

,id,identifier,fileId,pageCount,symbolId,securityName,fileSize,heading,dateTime,fileType,isPriceSensitive,fileKey,types,ticker
0,2029956,XASX:COF:2A1654634,2A1654634,25,COF:AUD:XASX,Centuria Office REIT,846523,Change in substantial holding,2026-02-19T21:20:50.000Z,pdf,False,announcements/xasx/2026/02/20/2A1654634.pdf,"[{'id': 5, 'identifier': '5', 'title': 'Securi...",COF
1,2023403,XASX:COF:2A1651396,2A1651396,33,COF:AUD:XASX,Centuria Office REIT,6901467,COF HY26 Property Compendium,2026-02-03T22:15:26.000Z,pdf,True,announcements/xasx/2026/02/04/2A1651396.pdf,"[{'id': 2, 'identifier': '2', 'title': 'Period...",COF
2,2023407,XASX:COF:2A1651393,2A1651393,37,COF:AUD:XASX,Centuria Office REIT,9235455,COF HY26 Results Presentation,2026-02-03T22:14:56.000Z,pdf,True,announcements/xasx/2026/02/04/2A1651393.pdf,"[{'id': 2, 'identifier': '2', 'title': 'Period...",COF
3,2023401,XASX:COF:2A1651392,2A1651392,3,COF:AUD:XASX,Centuria Office REIT,491231,COF HY26 Results Announcement,2026-02-03T22:14:16.000Z,pdf,True,announcements/xasx/2026/02/04/2A1651392.pdf,"[{'id': 2, 'identifier': '2', 'title': 'Period...",COF
4,2023390,XASX:COF:2A1651390,2A1651390,25,COF:AUD:XASX,Centuria Office REIT,2702614,COF HY26 Financial Report,2026-02-03T22:10:31.000Z,pdf,False,announcements/xasx/2026/02/04/2A1651390.pdf,"[{'id': 2, 'identifier': '2', 'title': 'Period...",COF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,53551,XASX:COF:2A1428487,2A1428487,4,COF:AUD:XASX,Centuria Office REIT,220199,COF HY23 Results Announcement,2023-02-01T22:21:38.000Z,pdf,True,announcements/xasx/2023/02/02/2A1428487.pdf,"[{'id': 2, 'identifier': '2', 'title': 'Period...",COF
96,53558,XASX:COF:2A1428484,2A1428484,26,COF:AUD:XASX,Centuria Office REIT,540542,COF HY23 Financial Report,2023-02-01T22:18:43.000Z,pdf,False,announcements/xasx/2023/02/02/2A1428484.pdf,"[{'id': 2, 'identifier': '2', 'title': 'Period...",COF
97,53564,XASX:COF:2A1428481,2A1428481,1,COF:AUD:XASX,Centuria Office REIT,395740,COF HY23 Appendix 4D,2023-02-01T22:17:03.000Z,pdf,True,announcements/xasx/2023/02/02/2A1428481.pdf,"[{'id': 4, 'identifier': '4', 'title': 'Divide...",COF
98,47147,XASX:COF:2A1425972,2A1425972,1,COF:AUD:XASX,Centuria Office REIT,163481,HY23 Results Date & Webcast Details,2023-01-17T04:07:09.000Z,pdf,False,announcements/xasx/2023/01/17/2A1425972.pdf,"[{'id': 15, 'identifier': '15', 'title': 'Othe...",COF
99,41611,XASX:COF:2A1425740,2A1425740,3,COF:AUD:XASX,Centuria Office REIT,151304,Change in substantial holding,2023-01-16T03:05:53.000Z,pdf,False,announcements/xasx/2023/01/16/2A1425740.pdf,"[{'id': 5, 'identifier': '5', 'title': 'Securi...",COF

In [ ]:
f"https://data-api.marketindex.com.au/api/v1/announcements?codes={ticker}%3AAUD%3AXASX&limit={limit}"

# To download all investor presentations for a set of tickers published between two dates.

In [21]:
#Inputs
# ticker_list = ["COF","CIP","CQR","CQE","ARF","CLW","GMG"]
# from_date_YYYY_MM_DD = "2020-01-31"
# to_date_YYYY_MM_DD = "2026-03-31"

ticker_list = ["INA","CHC","HDN","HCW","SGP","MGR","SCG","VCX","ABG","ASK","BWP","CMW","DXS","DXI","DXC","GLF","GPT","LIC","NSR","QAL","RGN","WPR","COF","CIP","CQR","CQE","ARF","CLW","GMG"]
from_date_YYYY_MM_DD = "2015-01-31"
to_date_YYYY_MM_DD = "2026-03-31"
save_dir = "datasets/raw"

#download statements for tickers in ticker list.  
dd.download_results_presentations(
    ticker_list = ticker_list,
    from_date_YYYY_MM_DD=from_date_YYYY_MM_DD,
    to_date_YYYY_MM_DD=to_date_YYYY_MM_DD,
    save_dir=save_dir,
    limit=500
    )

above ticker list
announcements run here
INA Change in substantial holding from MQG Security Holder Notices
INA 1H26 Property Portfolio Periodic Reports
INA 1H26 Results Presentation Other
INA Guidance Affirmed at Top of Range with Second Half Skew Other
INA Dividend/Distribution - INA Dividend Notices
INA Appendix 4D and Interim Financial Reports Dividend Notices
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Change in Directors' Interest Notices Security Holder Notices
INA Change in substantial holding Security Holder Notices
INA Initial Director's Interest Notice Security Holder Notices
INA Appointment of Non-Executive Director Company Administration
INA Becoming a substantial holder from MQG Security Holder Notices
INA Change in Director's Interest Notice - John Carfi Director Transactions
INA Notification regarding unquoted securities - INA Other
INA 2025 Annual General Meeting Results AGMs
INA 2025 AGM Chair and CEO Address and Presentation Other
INA Ceasing to be a substantial holder from MQG Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Notification regarding unquoted securities - INA Other
INA Notification of cessation of securities - INA Other
INA Notice of Meeting - 2025 Annual General Meeting AGMs
INA Change in Director's Interest Notice - John Carfi Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Ceasing to be a substantial holder Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Appendix 4G Other
INA 2025 Corporate Governance Statement Periodic Reports
INA 2025 Annual Report Annual Reports
INA Ceasing to be a substantial holder Security Holder Notices
INA Request for information from Consumer Affairs Victoria Company Administration
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA 2025 AGM and Closing Date for Director Nominations AGMs
INA FY25 Property Portfolio Periodic Reports
INA FY25 Results Presentation Other
INA Strategy Delivering - Underlying EPS Guidance Exceeded Periodic Reports
INA Dividend/Distribution - INA Dividend Notices
INA Appendix 4E and Financial Reports Dividend Notices
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Update on Deferred Management Fee Company Administration
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Change in substantial holding from MQG - Amendment Filing Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Change of Registered Office Address Company Administration
INA Change of Registry Address Company Administration
INA Notification of cessation of securities - INA Other
INA Notification regarding unquoted securities - INA Other
INA Change in substantial holding from MQG Security Holder Notices
INA Ceasing to be a Substantial Holder from HMC Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Notice of change of interests of substantial holder Security Holder Notices
INA HY25 Property Portfolio Periodic Reports
INA HY25 Results Presentation Other
INA Strong First Half Reflected in Recent FY25 Guidance Upgrade Periodic Reports
INA Dividend/Distribution - INA Dividend Notices
INA Appendix 4D and Interim Financial Reports Periodic Reports
INA Change in substantial holding Security Holder Notices
INA FY25 Guidance Increase Periodic Reports
INA Notification of cessation of securities - INA Other
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Ingenia winds up managed funds Other
INA Initial Director's Interest Notice - Jenny Fagg Security Holder Notices
INA Appointment of Non-Executive Director Company Administration
INA Final Director's Interest Notice - Jim Hazel Security Holder Notices
INA Final Director's Interest Notice - Sally Evans Security Holder Notices
INA Change in Director's Interest Notice - John Carfi Director Transactions
INA Notification regarding unquoted securities - INA Other
INA 2024 Annual General Meeting Results AGMs
INA 2024 AGM Chair and CEO Script and Presentation Other
INA Change in substantial holding Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Change in Director's Interest Notice - John Carfi Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Notice of Meeting - 2024 Annual General Meeting AGMs
INA Notification regarding unquoted securities - INA Other
INA Notification of cessation of securities - INA Other
INA Appendix 4G Other
INA 2024 Corporate Governance Statement Periodic Reports
INA 2024 Annual Report Periodic Reports
INA Change of Director's Interest Notice - Shane Gannon Director Transactions
INA Change in Director's Interest Notice - Shane Gannon Security Holder Notices
INA Response to ASX Aware Letter ASX Queries
INA Change in Director's Interest Notice - Simon Shakesheff Security Holder Notices
INA Change in substantial holding Security Holder Notices
INA Change in substantial holding from MQG Security Holder Notices
INA 2024 AGM Date and Closing Date for Nomination of Directors AGMs
INA FY24 Property Portfolio Periodic Reports
INA FY24 Results Presentation Other
INA Business Primed for Growth - Exceeding Guidance in FY24 Dividend Notices
INA Dividend/Distribution - INA Dividend Notices
INA Appendix 4E and Financial Statements FY24 Dividend Notices
INA Initial Director's Interest Notice - John Carfi Security Holder Notices
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Appointment of Executive Director Company Administration
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Change in substantial holding from MQG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Initial Directors' Interest Notices Security Holder Notices
INA Final Director's Interest Notice - Greg Hayes Security Holder Notices
INA Update on Board renewal Company Administration
INA Final Director's Interest Notice - Amanda Heyworth Security Holder Notices
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Appointment of Non Executive Directors and Board changes Company Administration
INA Trading and Guidance Update Other
INA Ingenia Update on Board changes Company Administration
INA Initial Director's Interest Notice - Lisa Scenna Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Notification of cessation of securities - INA Other
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Change in substantial holding Security Holder Notices
INA Appointment of Non Executive Director Company Administration
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Final Director's Interest Notice Security Holder Notices
INA 1H24 Property Portfolio Periodic Reports
INA 1H24 Results Presentation Other
INA Lifestyle and Holidays Businesses Delivering Growth Other
INA Dividend/Distribution - INA Dividend Notices
INA Appendix 4D and Half Year Report Dividend Notices
INA Change in substantial holding from HMC Security Holder Notices
INA Appointment of Chief Executive Officer Company Administration
INA Change in Director's Interest Notice - Simon Owen Security Holder Notices
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Becoming a substantial holder from MQG Security Holder Notices
INA Change of Director's Interest Notice - Simon Owen Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Results of AGM AGMs
INA AGM - Chair and CEO Address and Presentation Other
INA Ceasing to be a substantial holder from MQG Security Holder Notices
INA Simon Owen to depart as Ingenia CEO Company Administration
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA 2023 Sustainability Report Other
INA Environmental Policy Other
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Ingenia continues asset recycling program Other
INA EGH: Eureka-managed Fund acquires 6 villages in WA Other
INA Change in Director's Interest Notice - Simon Owen Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Becoming a substantial holder Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Becoming a substantial holder from MQG Security Holder Notices
INA Changes to the Ingenia Communities Group Board Company Administration
INA Final Director's Interest Notice - John McLaren Security Holder Notices
INA Corrected 2023 Annual Report Annual Reports
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Revised Remuneration Report Annual Reports
INA Ceasing to be a substantial holder Security Holder Notices
INA Change in Director's Interest Notice - Simon Owen Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Change in substantial holding Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Becoming a substantial holder from HMC Security Holder Notices
INA Change in Director's Interest Notice - John McLaren Director Transactions
INA Ceasing to be a substantial holder Security Holder Notices
INA 2023 Notice of Meeting AGMs
INA Notice of change of interests of substantial holder Security Holder Notices
INA Trading and divestment update Other
INA Change in Director's Interest Notice - Simon Owen Director Transactions
INA Notification regarding unquoted securities - INA Other
INA Notification of cessation of securities - INA Other
INA 2023 Corporate Governance Statement Periodic Reports
INA Appendix 4G Other
INA 2023 Annual Report Annual Reports
INA 2023 AGM and closing date for director nominations AGMs
INA Change in Director's Interest Notice - Sally Evans Security Holder Notices
INA Change in Director's Interest Notice - Greg Hayes Director Transactions
INA Notice of change in Director's Interest - Robert Morrison Director Transactions
INA FY23 Property Portfolio Periodic Reports
INA FY23 Results Presentation Periodic Reports
INA FY23 Results - Core business delivering growth Other
INA Dividend/Distribution - INA Dividend Notices
INA Appendix 4E and Financial Report for FY23 Dividend Notices
INA Terms agreed for JV extension Other
INA Notification of cessation of securities - INA Other
INA Becoming a substantial holder Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Ceasing to be a substantial holder from MQG Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Change of Director's Interest Notice - Simon Owen Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Sales and valuations update Other
INA Appendix 3Y - Simon Owen Security Holder Notices
INA Ingenia Communities trading update presentation Other
INA Ceasing to be a substantial holder Security Holder Notices
INA Change in Director's Interest Notice - Simon Owen Director Transactions
INA Appendix 3Y - Amanda Heyworth Security Holder Notices
INA Change in substantial holding Security Holder Notices
INA Becoming a substantial holder from MQG Security Holder Notices
INA Appointment of Chief Financial Officer Company Administration
INA Becoming a substantial holder Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Notification regarding unquoted securities - INA Other
INA Notification of cessation of securities - INA Other
INA Becoming a substantial holder Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA 1H23 Property Portfolio Other
INA 1H23 Results Presentation Other
INA Dividend/Distribution - INA Dividend Notices
INA Appendix 4D and Interim Financial Reports Periodic Reports
INA 1H23 Results and Guidance Update Periodic Reports
INA Trading Halt Trading Halts
INA Ceasing to be a substantial holder Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Executive Leadership Team Changes Company Administration
INA Notification of cessation of securities - INA Other
INA Change of Director's Interest Notice - Simon Owen Director Transactions
INA 2022 Sustainability Report Other
INA Notification regarding unquoted securities - INA Other
INA Results of Annual General Meeting AGMs
INA Annual General Meeting - Presentation Other
INA Annual General Meeting - Chair and CEO Address Other
INA Trading and Guidance Update Periodic Reports
INA Ingenia acquires new development projects Other
INA Ingenia commences asset recycling program Other
INA Ceasing to be a substantial holder from MUFG Security Holder Notices
INA Ceasing to be a substantial holder Security Holder Notices
INA Notice of Meeting - 2022 Annual General Meeting AGMs
INA Becoming a substantial holder from MUFG Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Change of Director's Interest Notice - Simon Owen Director Transactions
INA Notification of cessation of securities - INA Other
INA Notification regarding unquoted securities - INA Other
INA Appendix 4G Other
INA 2022 Corporate Governance Statement Periodic Reports
INA 2022 Annual Report Annual Reports
INA Change Notice of interests of substantial holder Security Holder Notices
INA Update - Dividend/Distribution - INA Dividend Notices
INA Change of Director's Interest Notice - Sally Evans Security Holder Notices
INA FY22 Property Portfolio Periodic Reports
INA FY22 Results Presentation Periodic Reports
INA FY22 Results Other
INA Appendix 4E and Financial Reports Dividend Notices
INA Dividend/Distribution - INA Dividend Notices
INA 2022 AGM and Closing Date for Nomination of Directors AGMs
INA Notification of cessation of securities - INA Other
INA Notification regarding unquoted securities - INA Other
INA Suspension of Distribution Reinvestment Plan Dividend Notices
INA Change in substantial holding Security Holder Notices
INA Becoming a substantial holder Security Holder Notices
INA Notification of cessation of securities - INA Other
INA Change of Director's Interest Notice Director Transactions
INA Appointment of Company Secretary Company Administration
INA FY22 Sales and Guidance Update Periodic Reports
INA Notification regarding unquoted securities - INA Other
INA Change of Director's Interest Notice Security Holder Notices
INA Trading and Guidance Update Periodic Reports
INA Notification regarding unquoted securities - INA Other
INA Appendix 3 Y - Mr John McLaren Security Holder Notices
INA Appendix 3Y- Ms Amanda Heyworth Security Holder Notices
INA Application for quotation of securities - INA Other
INA Update - Dividend/Distribution - INA Dividend Notices
INA Notification of cessation of securities - INA Other
INA Appendix 3 Y - Mr Simon Owen Director Transactions
INA Ingenia acquires three lifestyle communities in Melbourne Other
INA Appendix 3Y - Mr Greg Hayes Director Transactions
INA 1H22 Property portfolio Other
INA 1H22 Results announcement Periodic Reports
INA 1H22 Results presentation Other
INA Dividend/Distribution - INA Dividend Notices
INA Half Yearly Report and Accounts Dividend Notices
INA Ingenia acquires lifestyle community in South East QLD Periodic Reports
INA Appendix 3Y- Mr Simon Owen Security Holder Notices
INA Director Resignation - Mr Shiffman Security Holder Notices
INA Changes to Ingenia Communities Group Board Company Administration
INA Ingenia completes acquisition of Seachange and Caravan Parks Other
INA Change of Director's Interest Notice- Mr Robert Morrison Security Holder Notices
INA Change of Director's Interest Notice- Ms Phillipa Downes Director Transactions
INA Change of Director's Interest Notice- Ms Amanda Heyworth Director Transactions
INA Change of Director's Interest Notice- Mr Simon Owen Director Transactions
INA Application for quotation of securities - INA Other
INA Ingenia successfully completes Retail Entitlement Offer Capital Raises & Escrow
INA Change of Director's Interest Notice- Ms Sally Evans Security Holder Notices
INA Change of Director's Interest Notice- Mr John McLaren Director Transactions
INA Change of Director's Interest Notice- Mr Gary Shifman Director Transactions
INA Change of Director's Interest Notice- Mr Simon Owen Security Holder Notices
INA Change of Director's Interest Notice- Ms Sally Evans Director Transactions
INA Change of Director's Interest Notice- Mr James Hazel Director Transactions
INA Application for quotation of securities - INA Other
INA Jobkeeper Payments Notification Periodic Reports
INA Application for quotation of securities - INA Other
INA Notification regarding unquoted securities - INA Other
INA Results of AGM Election AGMs
INA Chairman's Address to Shareholders and  AGM Presentation Other
INA Notification of cessation of securities - INA Other
INA Ingenia acquires iconic, multi-awarded BIG4 Beacon Resort Other
INA Despatch of Retail Entitlement Offer Booklet Capital Raises & Escrow
INA Nominee Letter Other
INA Letter to Ineligible Security holders Other
INA Retail Entitlement Offer Booklet 2021 Other
INA Ingenia successfully completes institutional component Capital Raises & Escrow
INA Cleansing Statement Other
INA Proposed issue of securities - INA Non-Procedural
INA Acquisitions and Equity Raising Investor Presentation Periodic Reports
INA Ingenia announces $475m equity raise to fund acquisitions Other
INA Trading Halt Trading Halts
INA 2021 Sustainability Report Periodic Reports
INA Notice of Annual General Meeting/Proxy Form AGMs
INA Change of Director's Interest Notice - S Owen Security Holder Notices

C:\Users\chuak\AppData\Local\Temp\ipykernel_27984\2421094739.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ISO_date"] = pd.to_datetime(df['dateTime'])

Filtered 408 announcements matching the criteria.
Downloading  1H26 Results Presentation .....
INA_HY26_IP.pdf
<Response [200]>
Downloaded: INA_HY26_IP.pdf
Downloading  FY25 Results Presentation .....
INA_FY25_IP.pdf
<Response [200]>
Downloaded: INA_FY25_IP.pdf
Downloading  HY25 Results Presentation .....
INA_HY25_IP.pdf
<Response [200]>
Downloaded: INA_HY25_IP.pdf
Downloading  FY24 Results Presentation .....
INA_FY24_IP.pdf
<Response [200]>
Downloaded: INA_FY24_IP.pdf
Downloading  1H24 Results Presentation .....
INA_HY24_IP.pdf
<Response [200]>
Downloaded: INA_HY24_IP.pdf
Downloading  FY23 Results Presentation .....
INA_FY23_IP.pdf
<Response [200]>
Downloaded: INA_FY23_IP.pdf
Downloading  1H23 Results Presentation .....
INA_HY23_IP.pdf
<Response [200]>
Downloaded: INA_HY23_IP.pdf
Downloading  FY22 Results Presentation .....
INA_FY22_IP.pdf
<Response [200]>
Downloaded: INA_FY22_IP.pdf
Downloading  1H22 Results presentation .....
INA_HY22_IP.pdf
<Response [200]>
Downloaded: INA_HY22_IP.pdf
Downloading  FY21 Full Year Results Presentation .....
INA_FY21_IP.pdf
<Response [200]>
Downloaded: INA_FY21_IP.pdf
Downloading  1H21 Results Presentation .....
INA_HY21_IP.pdf
<Response [200]>
Downloaded: INA_HY21_IP.pdf
Downloading  FY2020 Results Presentation .....
INA_FY20_IP.pdf
<Response [200]>
Downloaded: INA_FY20_IP.pdf
Downloading  1H20 Results Presentation .....
INA_HY20_IP.pdf
<Response [200]>
Downloaded: INA_HY20_IP.pdf
Downloading  HY26 Results Presentation .....
CHC_HY26_IP.pdf
<Response [200]>
Downloaded: CHC_HY26_IP.pdf
Downloading  HY25 Results Presentation .....
CHC_HY25_IP.pdf
<Response [200]>
Downloaded: CHC_HY25_IP.pdf
Downloading  HY24 Results Presentation .....
CHC_HY24_IP.pdf
<Response [200]>
Downloaded: CHC_HY24_IP.pdf
Downloading  HY26 Results Presentation .....
HDN_HY26_IP.pdf
<Response [200]>
Downloaded: HDN_HY26_IP.pdf
Downloading  FY25 Results Presentation .....
HDN_FY25_IP.pdf
<Response [200]>
Downloaded: HDN_FY25_IP.pdf
Downloading  HY25 Results Presentation .....
HDN_HY25_IP.pdf
<Response [200]>
Downloaded: HDN_HY25_IP.pdf
Downloading  FY24 Results Presentation .....
HDN_FY24_IP.pdf
<Response [200]>
Downloaded: HDN_FY24_IP.pdf
Downloading  HY24 Results Presentation .....
HDN_HY24_IP.pdf
<Response [200]>
Downloaded: HDN_HY24_IP.pdf
Downloading  FY23 Results Presentation .....
HDN_FY23_IP.pdf
<Response [200]>
Downloaded: HDN_FY23_IP.pdf
Downloading  HY23 Results Presentation .....
HDN_HY23_IP.pdf
<Response [200]>
Downloaded: HDN_HY23_IP.pdf
Downloading  FY22 Results Presentation .....
HDN_FY22_IP.pdf
<Response [200]>
Downloaded: HDN_FY22_IP.pdf
Downloading  HY22 Financial Results Presentation .....
HDN_HY22_IP.pdf
<Response [200]>
Downloaded: HDN_HY22_IP.pdf
Downloading  FY21 Financial Results Presentation .....
HDN_FY21_IP.pdf
<Response [200]>
Downloaded: HDN_FY21_IP.pdf
Downloading  HDN - 1H FY21 Financial Results Presentation .....
HDN_HY21_IP.pdf
<Response [200]>
Downloaded: HDN_HY21_IP.pdf
Downloading  HY26 Results Presentation .....
HCW_HY26_IP.pdf
<Response [200]>
Downloaded: HCW_HY26_IP.pdf
Downloading  FY25 Results Presentation .....
HCW_FY25_IP.pdf
<Response [200]>
Downloaded: HCW_FY25_IP.pdf
Downloading  HY25 Results Presentation .....
HCW_HY25_IP.pdf
<Response [200]>
Downloaded: HCW_HY25_IP.pdf
Downloading  FY24 Results Presentation .....
HCW_FY24_IP.pdf
<Response [200]>
Downloaded: HCW_FY24_IP.pdf
Downloading  HY24 Results Presentation .....
HCW_HY24_IP.pdf
<Response [200]>
Downloaded: HCW_HY24_IP.pdf
Downloading  FY23 Results Presentation .....
HCW_FY23_IP.pdf
<Response [200]>
Downloaded: HCW_FY23_IP.pdf
Downloading  HY23 Results Presentation .....
HCW_HY23_IP.pdf
<Response [200]>
Downloaded: HCW_HY23_IP.pdf
Downloading  FY22 Results Presentation .....
HCW_FY22_IP.pdf
<Response [200]>
Downloaded: HCW_FY22_IP.pdf
Downloading  HY22 Financial Results Presentation .....
HCW_HY22_IP.pdf
<Response [200]>
Downloaded: HCW_HY22_IP.pdf
Downloading  1H26 Results Presentation .....
SGP_HY26_IP.pdf
<Response [200]>
Downloaded: SGP_HY26_IP.pdf
Downloading  Stockland FY25 Results Presentation .....
SGP_FY25_IP.pdf
<Response [200]>
Downloaded: SGP_FY25_IP.pdf
Downloading  1H25 Results Presentation .....
SGP_HY25_IP.pdf
<Response [200]>
Downloaded: SGP_HY25_IP.pdf
Downloading  Stockland FY24 Results Presentation .....
SGP_FY24_IP.pdf
<Response [200]>
Downloaded: SGP_FY24_IP.pdf
Downloading  1H24 Results Presentation .....
SGP_HY24_IP.pdf
<Response [200]>
Downloaded: SGP_HY24_IP.pdf
Downloading  Stockland FY23 Results Presentation .....
SGP_FY23_IP.pdf
<Response [200]>
Downloaded: SGP_FY23_IP.pdf
Downloading  1H23 Results Presentation .....
SGP_HY23_IP.pdf
<Response [200]>
Downloaded: SGP_HY23_IP.pdf
Downloading  Stockland FY22 Results Presentation .....
SGP_FY22_IP.pdf
<Response [200]>
Downloaded: SGP_FY22_IP.pdf
Downloading  1H22 Results Presentation .....
SGP_HY22_IP.pdf
<Response [200]>
Downloaded: SGP_HY22_IP.pdf
Downloading  Stockland FY21 Results Presentation .....
SGP_FY21_IP.pdf
<Response [200]>
Downloaded: SGP_FY21_IP.pdf
Downloading  1H21 Results Presentation Annexure .....
SGP_HY21_IP.pdf
<Response [200]>
Downloaded: SGP_HY21_IP.pdf
Downloading  1H21 Results Presentation .....
SGP_HY21_IP.pdf
Downloading  Stockland FY20 Results Presentation .....
SGP_FY20_IP.pdf
<Response [200]>
Downloaded: SGP_FY20_IP.pdf
Downloading  1H20 Results Presentation Annexure .....
SGP_HY20_IP.pdf
<Response [200]>
Downloaded: SGP_HY20_IP.pdf
Downloading  1H20 Results Presentation .....
SGP_HY20_IP.pdf
Downloading  FY19 Results Presentation .....
SGP_FY19_IP.pdf
<Response [200]>
Downloaded: SGP_FY19_IP.pdf
Downloading  1H19 Results Presentation Annexure .....
SGP_HY19_IP.pdf
<Response [200]>
Downloaded: SGP_HY19_IP.pdf
Downloading  1H19 Results Presentation .....
SGP_HY19_IP.pdf
Downloading  FY18 Results Presentation .....
SGP_FY18_IP.pdf
<Response [200]>
Downloaded: SGP_FY18_IP.pdf
Downloading  1H18 Results Presentation Annexure .....
SGP_HY18_IP.pdf
<Response [200]>
Downloaded: SGP_HY18_IP.pdf
Downloading  1H18 Results Presentation .....
SGP_HY18_IP.pdf
Downloading  MGR 1H26 Results Presentation .....
MGR_HY26_IP.pdf
<Response [200]>
Downloaded: MGR_HY26_IP.pdf
Downloading  MGR FY25 Results Presentation .....
MGR_FY25_IP.pdf
<Response [200]>
Downloaded: MGR_FY25_IP.pdf
Downloading  MGR 1H25 Results Presentation .....
MGR_HY25_IP.pdf
<Response [200]>
Downloaded: MGR_HY25_IP.pdf
Downloading  MGR FY24 Results Presentation .....
MGR_FY24_IP.pdf
<Response [200]>
Downloaded: MGR_FY24_IP.pdf
Downloading  MGR 1H24 Results Presentation .....
MGR_HY24_IP.pdf
<Response [200]>
Downloaded: MGR_HY24_IP.pdf
Downloading  MGR FY23 Results Presentation .....
MGR_FY23_IP.pdf
<Response [200]>
Downloaded: MGR_FY23_IP.pdf
Downloading  MGR 1H23 Results Presentation .....
MGR_HY23_IP.pdf
<Response [200]>
Downloaded: MGR_HY23_IP.pdf
Downloading  MGR FY22 Results Presentation .....
MGR_FY22_IP.pdf
<Response [200]>
Downloaded: MGR_FY22_IP.pdf
Downloading  MGR 1H22 Results Presentation .....
MGR_HY22_IP.pdf
<Response [200]>
Downloaded: MGR_HY22_IP.pdf
Downloading  MGR FY21 Results Presentation .....
MGR_FY21_IP.pdf
<Response [200]>
Downloaded: MGR_FY21_IP.pdf
Downloading  MGR 1H21 Results Presentation .....
MGR_HY21_IP.pdf
<Response [200]>
Downloaded: MGR_HY21_IP.pdf
Downloading  MGR FY20 Results Presentation .....
MGR_FY20_IP.pdf
<Response [200]>
Downloaded: MGR_FY20_IP.pdf
Downloading  MGR 1H20 Results Presentation .....
MGR_HY20_IP.pdf
<Response [200]>
Downloaded: MGR_HY20_IP.pdf
Downloading  MGR FY19 Results Presentation .....
MGR_FY19_IP.pdf
<Response [200]>
Downloaded: MGR_FY19_IP.pdf
Downloading  MGR 1H19 Results Presentation .....
MGR_HY19_IP.pdf
<Response [200]>
Downloaded: MGR_HY19_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY26_IP.pdf
<Response [200]>
Downloaded: SCG_HY26_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY25_IP.pdf
<Response [200]>
Downloaded: SCG_HY25_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY24_IP.pdf
<Response [200]>
Downloaded: SCG_HY24_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY23_IP.pdf
<Response [200]>
Downloaded: SCG_HY23_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY22_IP.pdf
<Response [200]>
Downloaded: SCG_HY22_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY21_IP.pdf
<Response [200]>
Downloaded: SCG_HY21_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY20_IP.pdf
<Response [200]>
Downloaded: SCG_HY20_IP.pdf
Downloading  Full Year Announcement and Results Presentation .....
SCG_HY19_IP.pdf
<Response [200]>
Downloaded: SCG_HY19_IP.pdf
Downloading  Full Year Results Media Release and Results Presentation .....
SCG_HY18_IP.pdf
<Response [200]>
Downloaded: SCG_HY18_IP.pdf
Downloading  ASX Announcement and Half-Year Results Presentation .....
SCG_FY17_IP.pdf
<Response [200]>
Downloaded: SCG_FY17_IP.pdf
Downloading  Full Year Results Media Release and Results Presentation .....
SCG_HY17_IP.pdf
<Response [200]>
Downloaded: SCG_HY17_IP.pdf
Downloading  SCG Media Release and Results Presentation .....
SCG_HY16_IP.pdf
<Response [200]>
Downloaded: SCG_HY16_IP.pdf
Downloading  FY26 Interim Results Presentation .....
VCX_HY26_IP.pdf
<Response [200]>
Downloaded: VCX_HY26_IP.pdf
Downloading  FY25 Annual Results Presentation .....
VCX_FY25_IP.pdf
<Response [200]>
Downloaded: VCX_FY25_IP.pdf
Downloading  FY25 Interim Results Presentation .....
VCX_HY25_IP.pdf
<Response [200]>
Downloaded: VCX_HY25_IP.pdf
Downloading  FY24 Annual Results Presentation .....
VCX_FY24_IP.pdf
<Response [200]>
Downloaded: VCX_FY24_IP.pdf
Downloading  FY24 interim results presentation .....
VCX_HY24_IP.pdf
<Response [200]>
Downloaded: VCX_HY24_IP.pdf
Downloading  FY23 annual results presentation .....
VCX_FY23_IP.pdf
<Response [200]>
Downloaded: VCX_FY23_IP.pdf
Downloading  FY23 interim results presentation .....
VCX_HY23_IP.pdf
<Response [200]>
Downloaded: VCX_HY23_IP.pdf
Downloading  FY22 annual results presentation .....
VCX_FY22_IP.pdf
<Response [200]>
Downloaded: VCX_FY22_IP.pdf
Downloading  FY22 interim results presentation .....
VCX_HY22_IP.pdf
<Response [200]>
Downloaded: VCX_HY22_IP.pdf
Downloading  FY21 annual results presentation .....
VCX_FY21_IP.pdf
<Response [200]>
Downloaded: VCX_FY21_IP.pdf
Downloading  FY21 interim results presentation .....
VCX_HY21_IP.pdf
<Response [200]>
Downloaded: VCX_HY21_IP.pdf
Downloading  FY20 annual results presentation .....
VCX_FY20_IP.pdf
<Response [200]>
Downloaded: VCX_FY20_IP.pdf
Downloading  FY20 interim results presentation .....
VCX_HY20_IP.pdf
<Response [200]>
Downloaded: VCX_HY20_IP.pdf
Downloading  FY19 annual results presentation .....
VCX_FY19_IP.pdf
<Response [200]>
Downloaded: VCX_FY19_IP.pdf
Downloading  FY19 interim results presentation .....
VCX_HY19_IP.pdf
<Response [200]>
Downloaded: VCX_HY19_IP.pdf
Downloading  HY26 Results Presentation .....
ABG_HY26_IP.pdf
<Response [200]>
Downloaded: ABG_HY26_IP.pdf
Downloading  FY25 Results Presentation .....
ABG_FY25_IP.pdf
<Response [200]>
Downloaded: ABG_FY25_IP.pdf
Downloading  HY25 Results Presentation .....
ABG_HY25_IP.pdf
<Response [200]>
Downloaded: ABG_HY25_IP.pdf
Downloading  FY24 Results Presentation .....
ABG_FY24_IP.pdf
<Response [200]>
Downloaded: ABG_FY24_IP.pdf
Downloading  HY24 Results Presentation .....
ABG_HY24_IP.pdf
<Response [200]>
Downloaded: ABG_HY24_IP.pdf
Downloading  FY23 Results Presentation .....
ABG_FY23_IP.pdf
<Response [200]>
Downloaded: ABG_FY23_IP.pdf
Downloading  FY22 Results Presentation .....
ABG_FY22_IP.pdf
<Response [200]>
Downloaded: ABG_FY22_IP.pdf
Downloading  HY22 results presentation .....
ABG_HY22_IP.pdf
<Response [200]>
Downloaded: ABG_HY22_IP.pdf
Downloading  FY21 Results Presentation .....
ABG_FY21_IP.pdf
<Response [200]>
Downloaded: ABG_FY21_IP.pdf
Downloading  Abacus HY21 Results Presentation .....
ABG_HY21_IP.pdf
<Response [200]>
Downloaded: ABG_HY21_IP.pdf
Downloading  ABP FY20 Results Presentation .....
ABG_FY20_IP.pdf
<Response [200]>
Downloaded: ABG_FY20_IP.pdf
Downloading  ABP HY20 Results Presentation and Data Pack .....
ABG_HY20_IP.pdf
<Response [200]>
Downloaded: ABG_HY20_IP.pdf
Downloading  ABP FY19 Results Presentation .....
ABG_FY19_IP.pdf
<Response [200]>
Downloaded: ABG_FY19_IP.pdf
Downloading  ABP HY19 results presentation and data pack .....
ABG_HY19_IP.pdf
<Response [200]>
Downloaded: ABG_HY19_IP.pdf
Downloading  ABP FY18 results presentation appendices .....
ABG_FY18_IP.pdf
<Response [200]>
Downloaded: ABG_FY18_IP.pdf
Downloading  ABP FY18 results presentation .....
ABG_FY18_IP.pdf
Downloading  ABP HY18 results presentation Appendices .....
ABG_HY18_IP.pdf
<Response [200]>
Downloaded: ABG_HY18_IP.pdf
Downloading  ABP HY18 results presentation .....
ABG_HY18_IP.pdf
Downloading  ABP FY17 results presentation appendicies .....
ABG_FY17_IP.pdf
<Response [200]>
Downloaded: ABG_FY17_IP.pdf
Downloading  ABP FY17 results presentation .....
ABG_FY17_IP.pdf
Downloading  ABP HY17 results presentation appendices .....
ABG_HY17_IP.pdf
<Response [200]>
Downloaded: ABG_HY17_IP.pdf
Downloading  ABP HY17 results presentation .....
ABG_HY17_IP.pdf
Downloading  HY26 Results Presentation .....
ASK_HY26_IP.pdf
<Response [200]>
Downloaded: ASK_HY26_IP.pdf
Downloading  HY25 Results Presentation .....
ASK_HY25_IP.pdf
<Response [200]>
Downloaded: ASK_HY25_IP.pdf
Downloading  HY24 Results Presentation .....
ASK_HY24_IP.pdf
<Response [200]>
Downloaded: ASK_HY24_IP.pdf
Downloading  HY26 Results Presentation .....
CMW_HY26_IP.pdf
<Response [200]>
Downloaded: CMW_HY26_IP.pdf
Downloading  FY25 Results Presentation .....
CMW_FY25_IP.pdf
<Response [200]>
Downloaded: CMW_FY25_IP.pdf
Downloading  HY25 Results Presentation .....
CMW_HY25_IP.pdf
<Response [200]>
Downloaded: CMW_HY25_IP.pdf
Downloading  FY24 Results Presentation .....
CMW_FY24_IP.pdf
<Response [200]>
Downloaded: CMW_FY24_IP.pdf
Downloading  HY24 Results Presentation .....
CMW_HY24_IP.pdf
<Response [200]>
Downloaded: CMW_HY24_IP.pdf
Downloading  FY23 Results Presentation .....
CMW_FY23_IP.pdf
<Response [200]>
Downloaded: CMW_FY23_IP.pdf
Downloading  HY23 Results Presentation .....
CMW_HY23_IP.pdf
<Response [200]>
Downloaded: CMW_HY23_IP.pdf
Downloading  FY22 Results Presentation .....
CMW_FY22_IP.pdf
<Response [200]>
Downloaded: CMW_FY22_IP.pdf
Downloading  HY22 Results Presentation .....
CMW_HY22_IP.pdf
<Response [200]>
Downloaded: CMW_HY22_IP.pdf
Downloading  FY21 Results Presentation .....
CMW_FY21_IP.pdf
<Response [200]>
Downloaded: CMW_FY21_IP.pdf
Downloading  HY21 Results Presentation .....
CMW_HY21_IP.pdf
<Response [200]>
Downloaded: CMW_HY21_IP.pdf
Downloading  FY20 Results Presentation .....
CMW_FY20_IP.pdf
<Response [200]>
Downloaded: CMW_FY20_IP.pdf
Downloading  HY20 Results Presentation .....
CMW_HY20_IP.pdf
<Response [200]>
Downloaded: CMW_HY20_IP.pdf
Downloading  FY19 Results Presentation .....
CMW_FY19_IP.pdf
<Response [200]>
Downloaded: CMW_FY19_IP.pdf
Downloading  HY19 Results Presentation .....
CMW_HY19_IP.pdf
<Response [200]>
Downloaded: CMW_HY19_IP.pdf
Downloading  FY18 Results Presentation .....
CMW_FY18_IP.pdf
<Response [200]>
Downloaded: CMW_FY18_IP.pdf
Downloading  HY26 Results presentation .....
DXS_HY26_IP.pdf
<Response [200]>
Downloaded: DXS_HY26_IP.pdf
Downloading  2025 Annual results presentation .....
DXS_FY25_IP.pdf
<Response [200]>
Downloaded: DXS_FY25_IP.pdf
Downloading  HY25 Results presentation .....
DXS_HY25_IP.pdf
<Response [200]>
Downloaded: DXS_HY25_IP.pdf
Downloading  2024 Annual Results Presentation .....
DXS_FY24_IP.pdf
<Response [200]>
Downloaded: DXS_FY24_IP.pdf
Downloading  HY24 Results presentation .....
DXS_HY24_IP.pdf
<Response [200]>
Downloaded: DXS_HY24_IP.pdf
Downloading  2023 Annual Results Presentation .....
DXS_FY23_IP.pdf
<Response [200]>
Downloaded: DXS_FY23_IP.pdf
Downloading  HY23 Results presentation .....
DXS_HY23_IP.pdf
<Response [200]>
Downloaded: DXS_HY23_IP.pdf
Downloading  2022 Annual Results presentation .....
DXS_FY22_IP.pdf
<Response [200]>
Downloaded: DXS_FY22_IP.pdf
Downloading  HY22 Results presentation .....
DXS_HY22_IP.pdf
<Response [200]>
Downloaded: DXS_HY22_IP.pdf
Downloading  2021 Annual Results Presentation and Property Synopsis .....
DXS_FY21_IP.pdf
<Response [200]>
Downloaded: DXS_FY21_IP.pdf
Downloading  HY21 Results presentation .....
DXS_HY21_IP.pdf
<Response [200]>
Downloaded: DXS_HY21_IP.pdf
Downloading  2020 Annual Results Presentation and Property Synopsis .....
DXS_FY20_IP.pdf
<Response [200]>
Downloaded: DXS_FY20_IP.pdf
Downloading  HY20 Results Presentation .....
DXS_HY20_IP.pdf
<Response [200]>
Downloaded: DXS_HY20_IP.pdf
Downloading  2019 Annual results presentation .....
DXS_FY19_IP.pdf
<Response [200]>
Downloaded: DXS_FY19_IP.pdf
Downloading  HY26 Results presentation .....
DXI_HY26_IP.pdf
<Response [200]>
Downloaded: DXI_HY26_IP.pdf
Downloading  FY25 Results presentation .....
DXI_FY25_IP.pdf
<Response [200]>
Downloaded: DXI_FY25_IP.pdf
Downloading  HY25 Results presentation .....
DXI_HY25_IP.pdf
<Response [200]>
Downloaded: DXI_HY25_IP.pdf
Downloading  FY24 Results presentation .....
DXI_FY24_IP.pdf
<Response [200]>
Downloaded: DXI_FY24_IP.pdf
Downloading  HY24 Results presentation .....
DXI_HY24_IP.pdf
<Response [200]>
Downloaded: DXI_HY24_IP.pdf
Downloading  FY23 Results presentation .....
DXI_FY23_IP.pdf
<Response [200]>
Downloaded: DXI_FY23_IP.pdf
Downloading  HY23 Results presentation .....
DXI_HY23_IP.pdf
<Response [200]>
Downloaded: DXI_HY23_IP.pdf
Downloading  FY22 Results presentation .....
DXI_FY22_IP.pdf
<Response [200]>
Downloaded: DXI_FY22_IP.pdf
Downloading  HY22 Results presentation .....
DXI_HY22_IP.pdf
<Response [200]>
Downloaded: DXI_HY22_IP.pdf
Downloading  FY21 Results Presentation .....
DXI_FY21_IP.pdf
<Response [200]>
Downloaded: DXI_FY21_IP.pdf
Downloading  Half Year Financial Results Presentation .....
DXI_HY21_IP.pdf
<Response [200]>
Downloaded: DXI_HY21_IP.pdf
Downloading  FY2020 Annual Results Presentation .....
DXI_FY20_IP.pdf
<Response [200]>
Downloaded: DXI_FY20_IP.pdf
Downloading  Half Year Financial Results Presentation .....
DXI_HY20_IP.pdf
<Response [200]>
Downloaded: DXI_HY20_IP.pdf
Downloading  FY2019 Results Presentation .....
DXI_FY19_IP.pdf
<Response [200]>
Downloaded: DXI_FY19_IP.pdf
Downloading  Half Year Financial Results Presentations - 31 December 2018 .....
DXI_HY19_IP.pdf
<Response [200]>
Downloaded: DXI_HY19_IP.pdf
Downloading  FY18 Financial Results Presentation .....
DXI_FY18_IP.pdf
<Response [200]>
Downloaded: DXI_FY18_IP.pdf
Downloading  Half Year Financial Results Presentation - 31 December 2017 .....
DXI_HY18_IP.pdf
<Response [200]>
Downloaded: DXI_HY18_IP.pdf
Downloading  FY17 Financial Results Presentation - 30 June 2017 .....
DXI_FY17_IP.pdf
<Response [200]>
Downloaded: DXI_FY17_IP.pdf
Downloading  Half Year Financial Results Presentation - 31 December 2016 .....
DXI_HY17_IP.pdf
<Response [200]>
Downloaded: DXI_HY17_IP.pdf
Downloading  FY16 Financial Results Presentation - 30 June 2016 .....
DXI_FY16_IP.pdf
<Response [200]>
Downloaded: DXI_FY16_IP.pdf
Downloading  Half Year Financial Results Presentation - 31 December 2015 .....
DXI_HY16_IP.pdf
<Response [200]>
Downloaded: DXI_HY16_IP.pdf
Downloading  HY26 Results presentation .....
DXC_HY26_IP.pdf
<Response [200]>
Downloaded: DXC_HY26_IP.pdf
Downloading  FY25 Results presentation .....
DXC_FY25_IP.pdf
<Response [200]>
Downloaded: DXC_FY25_IP.pdf
Downloading  HY25 Results presentation .....
DXC_HY25_IP.pdf
<Response [200]>
Downloaded: DXC_HY25_IP.pdf
Downloading  FY24 Results presentation .....
DXC_FY24_IP.pdf
<Response [200]>
Downloaded: DXC_FY24_IP.pdf
Downloading  HY24 Results presentation .....
DXC_HY24_IP.pdf
<Response [200]>
Downloaded: DXC_HY24_IP.pdf
Downloading  FY23 Results presentation .....
DXC_FY23_IP.pdf
<Response [200]>
Downloaded: DXC_FY23_IP.pdf
Downloading  HY23 Results presentation .....

# Analyze what announcements are available

In [24]:
dd.create_announcement_df(ticker_list= ticker_list, limit=100).head()

,id,identifier,fileId,pageCount,symbolId,securityName,fileSize,heading,dateTime,fileType,isPriceSensitive,fileKey,types,ticker
0,1909132,XASX:COF:2A1600573,2A1600573,1,COF:AUD:XASX,Centuria Office REIT,169606,June 2025 Distribution Declaration,2025-06-05T23:07:10.000Z,pdf,True,announcements/xasx/2025/06/06/2A1600573.pdf,"[{'id': 4, 'identifier': '4', 'title': 'Divide...",COF
1,1909129,XASX:COF:2A1600570,2A1600570,4,COF:AUD:XASX,Centuria Office REIT,13770,Dividend/Distribution - COF,2025-06-05T23:04:25.000Z,pdf,True,announcements/xasx/2025/06/06/2A1600570.pdf,"[{'id': 4, 'identifier': '4', 'title': 'Divide...",COF
2,1901199,XASX:COF:2A1596683,2A1596683,2,COF:AUD:XASX,Centuria Office REIT,231397,Q3 FY25 Operating Update,2025-05-14T23:07:04.000Z,pdf,True,announcements/xasx/2025/05/15/2A1596683.pdf,"[{'id': 2, 'identifier': '2', 'title': 'Period...",COF
3,1874219,XASX:COF:2A1583347,2A1583347,1,COF:AUD:XASX,Centuria Office REIT,169175,March 2025 Distribution Declaration,2025-03-06T22:44:26.000Z,pdf,True,announcements/xasx/2025/03/07/2A1583347.pdf,"[{'id': 4, 'identifier': '4', 'title': 'Divide...",COF
4,1874212,XASX:COF:2A1583345,2A1583345,4,COF:AUD:XASX,Centuria Office REIT,13770,Dividend/Distribution - COF,2025-03-06T22:39:21.000Z,pdf,True,announcements/xasx/2025/03/07/2A1583345.pdf,"[{'id': 4, 'identifier': '4', 'title': 'Divide...",COF

# To download specific reports available in Announcement Dataframe

In [ ]:
#Inputs
regex_pattern = r'operating update'
from_date_YYYY_MM_DD="2024-01-31"
to_date_YYYY_MM_DD="2025-03-31",
save_dir="datasets/raw"
limit = 100


dd.download_documents(
    ticker_list=ticker_list,
    from_date_YYYY_MM_DD=from_date_YYYY_MM_DD,
    to_date_YYYY_MM_DD=to_date_YYYY_MM_DD,
    save_dir=save_dir,
    regex_pattern=regex_pattern,
    limit=limit
)

/tmp/ipykernel_5569/1988005279.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ISO_date"] = pd.to_datetime(df['dateTime'])

Filtered 2 announcements matching the criteria.
Downloading  Q1 FY25 Operating Update .....
<Response [200]>
Downloaded: COF_Q1 FY25 Operating Update
Downloading  Q3 FY24 Operating Update .....
<Response [200]>
Downloaded: COF_Q3 FY24 Operating Update

In [ ]:
tickers_prospectus = [
    "GYG", "DGT", "TEA", "MAC", "CCL", "SYL", "MRE", "WHI", "PCX", "BWN",
    # "SS1", "VFY", "GHM", "BB1", "AAL", "WAG", "D3E", "ORD", "RNV", "RAU",
    # "AXL", "MNC", "PR2", "KM1", "FNR", "I88", "MHM", "LMS", "FUL"
]